-- ============================================
-- Миграция V001: Создание исходной структуры БД
-- ============================================

-- Таблица товаров
CREATE TABLE IF NOT EXISTS product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    picture_url VARCHAR(255)
);

-- Таблица с информацией о товарах (дублирует product)
CREATE TABLE IF NOT EXISTS product_info (
    product_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    price DOUBLE PRECISION
);

-- Таблица заказов
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(255)
);

-- Таблица с датами заказов (дублирует orders)
CREATE TABLE IF NOT EXISTS orders_date (
    order_id BIGINT NOT NULL,
    status VARCHAR(255),
    date_created DATE DEFAULT CURRENT_DATE
);

-- Таблица связей заказов и товаров
CREATE TABLE IF NOT EXISTS order_product (
    quantity INTEGER NOT NULL,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL
);

