name: Main workflow

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      # Отладка ворнинга Warning: Node.js 20 is deprecated. The following actions target Node.js 20 but are being forced to run on Node.js 24: actions/checkout@v4.
      # FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flyway
        run: |
          wget -qO- https://download.red-gate.com/maven/release/com/redgate/flyway/flyway-commandline/10.10.0/flyway-commandline-10.10.0-linux-x64.tar.gz | tar xvz
          sudo ln -s $(pwd)/flyway-10.10.0/flyway /usr/local/bin/flyway
          flyway --version

      - name: Run Flyway migrations
        run: |
          flyway -url=jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }} \
                 -user=${{ secrets.DB_USER }} \
                 -password=${{ secrets.DB_PASSWORD }} \
                 -locations=filesystem:./migrations \
                 -baselineOnMigrate=true \
                 migrate

      - name: Show migration info
        run: |
          flyway -url=jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }} \
                 -user=${{ secrets.DB_USER }} \
                 -password=${{ secrets.DB_PASSWORD }} \
                 info

      - name: Download and setup autotests binaries
        run: |
          wget -qO- cloud-services-engineer.gitlab.yandexcloud.net/practicum-cloud-services/dbops-autotests/-/package_files/1/download > dbopstest
          chmod +x ./dbopstest
          mv ./dbopstest /usr/local/bin/dbopstest

      - name: Test
        run: |
          dbopstest \
            -test.v \
            -host=${{ secrets.DB_HOST }} \
            -port=${{ secrets.DB_PORT }} \
            -user=${{ secrets.DB_USER }} \
            -password=${{ secrets.DB_PASSWORD }} \
            -db=${{ secrets.DB_NAME }}
